### ISSUE TITLE
NewsFeed API endpoint

### ISSUE THREAD

**Issue by dealloc** [Mitcheljager/helldiverstrainingmanual#3]
Hi @Mitcheljager I'm the maintainer of https://github.com/dealloc/helldivers2-api

I was wondering if you'd be willing to share how you got a hold of the NewsFeed endpoint?

**Comment by Mitcheljager** [comment]
Sure! The creator of https://helldiverscompanion.com/ shared it with me, along with this endpoint; https://api.live.prod.thehelldiversgame.com/api/v2/Assignment/War/801, which shows the current Major Order. It's empty as of writing this message, but that might be different in time.
