### ISSUE TITLE
[Feature request] Add linking to breadcrumbs in navigation pages

### ISSUE THREAD

**Issue by emmyrlim** [Mitcheljager/helldiverstrainingmanual#5]
Hey @Mitcheljager this is pretty cool. I'd like to be able to contribute.

I've added additional linking in the Bestiary and Stratagem pages for your consideration:
https://github.com/Mitcheljager/helldiverstrainingmanual/pull/4

**Comment by Mitcheljager** [comment]
Great idea, merged with https://github.com/Mitcheljager/helldiverstrainingmanual/pull/4
